## --- 基本設定（色や表示のみ） ---
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set-option -g history-limit 64096
set -sg escape-time 10

## --- キーバインド設定 ---
set-window-option -g mode-keys vi

## --- 外部ファイルの読み込み（見た目部分のみ） ---
source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

## --- プラグイン管理 ---
set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
